food/urls.py
from pathlib import Path
from django.urls import path

from .views import index,item,detail,create_item,ItemUpdateView,ItemDeleteView,my_view,HomePage,ItemDetailView,ItemCreateView

app_name = "food"

urlpatterns = [
    path('',HomePage.as_view(),name='index'),
    path('item/',item,name='item'),
    path('detail/<int:pk>/',ItemDetailView.as_view(),name='detail'),
    path('add/',ItemCreateView.as_view(),name='add'),
    path('update/<int:pk>/',ItemUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',ItemDeleteView.as_view(),name='delete'),
    path('my_view',my_view,name='my_view'),
 
]

my_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('food/',include('food.urls')),
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url='/food')),
    # path('accounts/',include('django.contrib.auth.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    
    path('register/',user_views.register,name='register'),
    
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path,include

app_name = 'users'

food/models.py
from dataclasses import fields
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.urls import reverse
# Create your models here.


    


class Item(models.Model):
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    img = models.CharField(max_length=500,default='https://cdn.dribbble.com/users/1012566/screenshots/4187820/media/985748436085f06bb2bd63686ff491a5.jpg?compress=1&resize=400x300&vertical=top')
    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    
    
    
    # Queryset is collection of objects stored in database
    # Manager is something we have at least in one model
    # Model makes simple to interact with database ,it uses orm(object relational mapper) for sql commands
    # item.objects.all()
    # where item is model , object is Manager and all is Method

class ItemInstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    
    item = models.ForeignKey('Item',on_delete=models.SET_NULL,null=True)
    ordered_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    def __str__(self):
        return self.item.item_name
    

    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,)
    img = models.ImageField(default='default.png',upload_to='profile_pictures')
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username
    

food/forms.py
from dataclasses import fields
from socket import fromshare
from django import forms
from .models import Item
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields='__all__'
        
        
class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

users/forms.py
from dataclasses import fields
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

food/views.py
from msilib.schema import ListView
from multiprocessing.util import is_abstract_socket_namespace
from re import template
from django.shortcuts import render
from .models import Item
from .forms import ItemForm
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect
from django.views.generic import UpdateView,DeleteView,ListView,DetailView,CreateView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def index(request):
    item_list=Item.objects.all()
    context = {
        'item_list':item_list
    }
    return render(request,'food/index.html',context=context)

class HomePage(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'



def item(request):
    return render(request,'food/item.html')


def detail(request,pk):
    item = Item.objects.get(pk=pk)
    context = {'item':item}
    return render(request,'food/detail.html',context=context)

class ItemDetailView(DetailView):
    model = Item
    template_name = 'food/detail.html'
    


def create_item(request):
        # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ItemForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            form.cleaned_data.save()
            return HttpResponseRedirect(reverse('food:index'))

    else:
        form = ItemForm()

    return render(request, 'food/item_form.html', {'form': form})

class ItemCreateView(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','img']
    template_name = 'food/item_form.html'
    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)
    
    


class ItemUpdateView(LoginRequiredMixin,UpdateView):
    model = Item
    form_class = ItemForm
    
    
    success_url = '/'

class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy('food:index')

@login_required
def my_view(request):
    return render(request,'food/my_view.html')

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.urls import reverse
from .forms import RegisterForm

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome  {username},your account is created')
            return redirect('login')
    else:
        form = RegisterForm()    
    return render (request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/detail.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <div class="row">
      <div class="col-8 mt-3">
        <div class="card" style="width:18rem;">
            <img src="{{item.img}}" class="card-img-top" height='150px'  alt="...">
            <div class="card-body">
              <h5 class="card-title">{{item.item_name}}</h5>
              <p class="card-text">{{item.item_desc}}</p>
              <p class="card-text">Rs: {{item.item_price}}</p>
              <a href="{% url 'food:index' %}" class="btn btn-primary">Go To Index Page</a>
            </div>
          </div>



      </div>
    
    </div>
  </div>



{% endblock content %}

food/templates/food/index.html
{% extends 'base.html' %}

{% block title %}

Home page
{% endblock title %}




{% block content %}


<div class="container">
   <div class="row">
     {% for item in item_list  %}
     <div class="col mt-3">
        <div class="card" style="width: 18rem;">
           <img src="{{item.img}}" height="150px" width='150px' class="card-img-top" alt="...">
        
           <div class="card-body">
              <h5 class="card-title">{{item.item_name}}</h5>
              <p class="card-text">{{item.item_desc}}</p>
              <p class="card-text">NPR: {{item.item_price}}</p>
              <a href="{% url 'food:detail' item.id %}" class='btn btn-success'>Details</a>
              <a href="{% url 'food:update' item.id %}" class='btn btn-success'>Update</a>
              <a href="{% url 'food:delete' item.id %}" class='btn btn-danger'>Delete</a>
              <a href="{% url 'profile'%}" class='btn btn-danger'>{{item.user_name}}</a>
           </div>
         </div>
        
     
     </div>
     {% endfor %}
  
   </div>

  </div>
{% endblock content %}

food/templates/food/item.html
{% extends 'base.html' %}
{% block content %}

<h1>This is item view</h1>
{% endblock content %}

food/templates/food/item_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Delete {{item.item_name}}

{% endblock title %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{item.item_name}}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

{% endblock content %}

food/templates/food/item_form.html
{% extends 'base.html' %}
{% block title %}
Fill Form

{% endblock title %}
{% block content %}

<div class="container mt-4">
    
    <form action="" method="post">
        {% csrf_token %}
        {{form.errors}}
        <section class="vh-100" style="background-color: #A77979">
            <div class="container h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-9">
          
                  <h1 class="text-white mb-4">Add a Item</h1>
          
                  <div class="card" style="border-radius: 15px;">
                    <div class="card-body">
          
     
                      <div class="row align-items-center pt-4 pb-3">
                        <div class="col-md-3 ps-5">
          
                          <h6 class="mb-0">Item name</h6>
          
                        </div>
                        <div class="col-md-9 pe-5">
          
                          <input type="text" name='item_name' class="form-control form-control-lg" />
          
                        </div>
                      </div>
          
                      <hr class="mx-n3">
                      <div class="row align-items-center pt-4 pb-3">
                        <div class="col-md-3 ps-5">
          
                          <h6 class="mb-0">Item Description</h6>
          
                        </div>
                        <div class="col-md-9 pe-5">
          
                          <input type="text" name='item_desc' class="form-control form-control-lg" />
          
                        </div>
                      </div>
          
                      <hr class="mx-n3">
                      <div class="row align-items-center pt-4 pb-3">
                        <div class="col-md-3 ps-5">
          
                          <h6 class="mb-0">Item price</h6>
          
                        </div>
                        <div class="col-md-9 pe-5">
          
                          <input type="number" name='item_price' class="form-control form-control-lg" />
          
                        </div>
                      </div>
          
                      <hr class="mx-n3">
                      <div class="row align-items-center pt-4 pb-3">
                        <div class="col-md-3 ps-5">
          
                          <h6 class="mb-0">Image Link</h6>
          
                        </div>
                        <div class="col-md-9 pe-5">
          
                          <input type="text" name='img'  class="form-control form-control-lg" value='https://cdn.dribbble.com/users/1012566/screenshots/4187820/media/985748436085f06bb2bd63686ff491a5.jpg?compress=1&resize=400x300&vertical=top' />
          
                        </div>
                      </div>
          
                      <hr class="mx-n3">
          
           
         
          
                      <div class="px-5 py-4">
                        <button type="submit" class="btn btn-primary btn-lg">Add Item</button>
                      </div>
          
                    </div>
                  </div>
          
                </div>
              </div>
            </div>
          </section>
    </form>


</div>



{% endblock content %}

food/templates/food/iteminstance_form.html
{% extends 'base.html' %}

{% block title %}
    Order

{% endblock title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Order Now">

</form>

{% endblock content %}

food/templates/food/my_view.html
{% include 'base.html' %}

{% block title %}

{% endblock title %}
{% block content %}
<h1>Logged in users only</h1>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% comment %}
  <link rel="stylesheet" href="{% static 'food/style.css' %}"> {% endcomment %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  {% block customCss %}


  {% endblock customCss %}
  <title>
    {% block index %}
    
    {% endblock index %}

  </title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'food:index' %}">Food App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'food:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'food:add' %}">Add Item</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>

          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log out</a>

          </li>
         
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
     

          {% endif %}
        
         




        </ul>
      </div>
    </div>
  </nav>
  {% if messages %}
  {% for message in messages  %}
  <div class="alert alert-{{ message.tags}}">

    {{message}}
  </div>


  {% endfor %}
  {% endif %}


  {% block content %}





  {% endblock content %}
    {% comment %} footer starts here {% endcomment %}

    <footer class="bg-dark text-center text-white">
      <!-- Grid container -->
      <div class="container p-4 pb-0">
        <!-- Section: Form -->
        <section class="">
          <form action="">
            <!--Grid row-->
            <div class="row d-flex justify-content-center">
              <!--Grid column-->
              <div class="col-auto">
                <p class="pt-2">
                  <strong>Sign up for our newsletter</strong>
                </p>
              </div>
              <!--Grid column-->
    
              <!--Grid column-->
              <div class="col-md-5 col-12">
                <!-- Email input -->
                <div class="form-outline form-white mb-4">
                  <input type="email" id="form5Example29" class="form-control" />
                  <label class="form-label" for="form5Example29">Email address</label>
                </div>
              </div>
              <!--Grid column-->
    
              <!--Grid column-->
              <div class="col-auto">
                <!-- Submit button -->
                <button type="submit" class="btn btn-outline-light mb-4">
                  Subscribe
                </button>
              </div>
              <!--Grid column-->
            </div>
            <!--Grid row-->
          </form>
        </section>
        <!-- Section: Form -->
      </div>
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
      </div>
      <!-- Copyright -->
    </footer>


    {% comment %} footer ends here  {% endcomment %}





  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
  </script>
</body>

</html>

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block index %}
Login
{% endblock index %}

{% block content %}
<section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
            class="img-fluid" alt="Sample image">
        </div>
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
          <form action='' method='post'>
            {% csrf_token %}
            <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
              <p class="lead fw-normal mb-0 me-3">Sign in</p>
        
            </div>
  
            <div class="divider d-flex align-items-center my-4">
              <p class="text-center fw-bold mx-3 mb-0"></p>
            </div>
  
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="text" name='username' id="form3Example3" class="form-control form-control-lg"
                placeholder="Enter a valid email address" />
              <label class="form-label" for="form3Example3">Username</label>
            </div>
  
            <!-- Password input -->
            <div class="form-outline mb-3">
              <input type="password" name='password' id="form3Example4" class="form-control form-control-lg"
                placeholder="Enter password" />
              <label class="form-label" for="form3Example4">Password</label>
            </div>
  
            <div class="d-flex justify-content-between align-items-center">
              <!-- Checkbox -->
              <div class="form-check mb-0">
                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                <label class="form-check-label" for="form2Example3">
                  Remember me
                </label>
              </div>
              <a href="#!" class="text-body">Forgot password?</a>
            </div>
  
            <div class="text-center text-lg-start mt-4 pt-2">
              <button type="submit" class="btn btn-primary btn-lg"
                style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
              <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'register' %}"
                  class="link-danger">Register</a></p>
            </div>
  
          </form>
        </div>
      </div>
    </div>
    
    </div>
  </section>


{% endblock content %}

users/templates/users/logout.html
{% extends 'base.html' %}

{% block index   %}

Log Out

{% endblock index   %}


{% block content %}

<h1>You are logged out</h1>

<a href="{% url 'login' %}" class='btn btn-secondary'>Log In</a>



{% endblock content %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block index %}
Profile


{% endblock index %}

{% block content %}

    <h1>{{user.username}}</h1>
    <img height='100px' src="{{ user.profile.img.url }}" alt="">

{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block customCss %}

{% endblock customCss %}


{% block index %}
    Registration

{% endblock index %}







{% block content %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
  
                  <form method='post' action='' class="mx-1 mx-md-4">
                    {% csrf_token %}
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" id="form3Example1c" name='first_name' class="form-control" />
                        <label class="form-label" for="form3Example1c">First Name</label>
                      </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" id="form3Example1c" name='last_name' class="form-control" />
                        <label class="form-label" for="form3Example1c">Last Name</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" name='username' id="form3Example3c" class="form-control" />
                        <label class="form-label" for="form3Example3c">Your Username</label>
                      </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="email" name='email' id="form3Example3c" class="form-control" />
                        <label class="form-label" for="form3Example3c">Your Email</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password" name='password1'id="form3Example4c" class="form-control" />
                        <label class="form-label" for="form3Example4c">Password</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password" name='password2' id="form3Example4cd" class="form-control" />
                        <label class="form-label" for="form3Example4cd">Repeat your password</label>
                      </div>
                    </div>
  
                    <div class="form-check d-flex justify-content-center mb-5">
                      <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                      <label class="form-check-label" for="form2Example3">
                        I agree all statements in <a href="#!">Terms of service</a>
                      </label>
                    </div>
  
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Register</button>
                    </div>
  
                  </form>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>



{% endblock content %}

users/templates/users/test.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

</body>
</html>